dist: trusty
language: node_js
node_js:
  - "8"
before_install:
  - npm install -g ethereumjs-testrpc
  - npm install -g truffle
  - npm install ipfs --global

script:
  - testrpc > testrpc.log &
  - jsipfs daemon
  - sleep 5
  - npm test
after_script:
  - cat testrpc.log
